[palette]
_white = "#f2f2f2"
_gray = "#A6A6A6"
_black = "#212121"
_blacker = "#000000"
_purple = "#9D62D9"
_light_purple = "#BA8EE6" # BA8EE6 B898D9
_blue = "#6291d9"
_light_blue = "#8eb1e5"
_dim_blue = "#264f78"
_dimmer_blue = "#162d45"
_cyan = "#5cccc6"
_neon_green = "#75e67d"
_neon_yellow = "#d0ff00"
_hot_pink = "#e6509b"
_orange = "#fdbe00"
_red = "#e83841"
_green = "#85db18"

# IDEA: comments should be "type green" and we should not highlight types

#..........Sublime Text
[sublime]
todo = 0

#..........VS Code
[vs_code]
type = "Dark"
name = "zooce-dark"
file = "./vscode/themes/zooce-dark-3-color-theme.json"

[vs_code.colors]
_white = [
    "editor.foreground",
]
_gray = [
]
_black = [
    "editor.background",
]
_blacker = [
    "editor.lineHighlightBackground",
    "editorGutter.background",
]
_dim_blue = [
    "editor.findMatchHighlightBackground",
    "editor.hoverHighlightBackground",
    "editor.wordHighlightBackground",
]
_dimmer_blue = [
    "editor.selectionHighlightBackground",
    "editor.symbolHighlightBackground",
]
_neon_yellow = [
    # "editor.selectionHighlightBorder",
    "editorBracketMatch.border",
    "editor.findMatchBorder",
]

[vs_code.tokenColors]
_white = [
    "constant.other.caps",
    "variable",
    "support.type.property-name",
    # "entity.name.type",
]
_gray = [
    "comment.block",
    "constant.character.format",
    "entity.name.function.decorator",
    "keyword.operator",
    "markup.fenced_code",
    "meta.attribute",
    "meta.brace",
    "meta.diff",
    "meta.embedded.diff",
    "meta.separator",
    "meta.tag",
    "meta.tag.preprocessor",
    "punctuation.accessor",
    "punctuation.brackets",
    "punctuation.comma",
    "punctuation.decorator",
    "punctuation.definition.annotation",
    "punctuation.definition.arguments",
    "punctuation.definition.begin",
    "punctuation.definition.block",
    "punctuation.definition.bold",
    "punctuation.definition.constant",
    "punctuation.definition.dict",
    "punctuation.definition.end",
    "punctuation.definition.italic",
    "punctuation.definition.link",
    "punctuation.definition.list",
    "punctuation.definition.metadata",
    "punctuation.definition.parameters",
    "punctuation.definition.quote",
    "punctuation.definition.raw",
    "punctuation.definition.string",
    "punctuation.definition.tag",
    "punctuation.definition.template-expression",
    "punctuation.parenthesis",
    "punctuation.section",
    "punctuation.semi",
    "punctuation.separator",
    "punctuation.terminator",
    "punctuation.other.period",
    "punctuation.other.comma",
    "punctuation.definition.imports",
    "punctuation.definition.annotation-arguments",
    "punctuation.definition.entity",
    "punctuation.definition.keyValuePair.toml",
    "punctuation.definition.inlinetable.toml",
    "punctuation.definition.array.toml",
    "storage.type.annotation",
    "string.quoted.docstring",
]
_purple = [
    "entity.name.tag",
    "keyword",
    "keyword.operator.delete",
    "keyword.operator.new",
    "markup.heading",
    "punctuation.definition.keyword",
    "punctuation.separator.namespace",
]
_light_purple = [
    "entity.name.type",
]
_blue = [
    "keyword.control.svelte",
    "punctuation.definition.keyword.svelte",
    "storage",
    "support.type",
    "support.class",
    "constant.other.database-name",
]
_light_blue = [
    "string",
    "support.constant.font-name",
    "support.constant.property-value",
    "constant.other.table-name",
# "entity.name.type",
]
_cyan = [
    "entity.name.function",
    "entity.other.attribute-name",
    "meta.function-call",
    "support.function",
    "entity.name.function.preprocessor",
    "entity.name.section",
]
_neon_green = [
    "variable.language", # like `self`
    # "comment.line",
    # "comment.block.html",
    # "comment.block.xml",
    "markup.raw",
    "markup.inline",
]
_neon_yellow = [
    "constant.numeric",
    "constant.language",
    "constant.character",
    "constant.other",
    "support.constant",
    "keyword.constant",
]
_hot_pink = [
    # "variable.language", # like `self`
    "comment.line",
    "comment.block.html",
    "comment.block.xml",
]
_orange = [
    "markup.changed",
]
_red = [
    "markup.deleted",
]
_green = [
    "markup.inserted",
]

#..........Vim
[vim.colors]
_gray = [
    "Comment",
    "String",
    "Identifier",
]
