_white = "#e6e6e6"
_gray = "#999999"
_black = "#212121"
_blacker = "#000000"
_purple = "#477acc" # 9D62D9 CC7570
_light_purple = "#BA8EE6" # BA8EE6 B898D9 a070c2
_blue = "#a2cc66" # 6291d9 669BCC
_light_blue = "#a2cc66" # 8eb1e5
_dim_blue = "#264f78"
_dimmer_blue = "#162d45"
_cyan = "#cc9947" # 5cccc6 95CC85
_neon_green = "#CC9A47" # 75e67d
_neon_yellow = "#52CC81" # d0ff00
_hot_pink = "#cc528b" # e6509b CC66BB
_orange = "#fdbe00"
_red = "#e83841"
_green = "#85db18"

_foreground = "#e6e6e6"
_punctuation = "#999999"
_background = "#212121"
_background_highlight = "#000000"
_keywords = "#cc6674" # fn, if, operators, modifiers, etc.
_storage = "#cc6674" # let, mut, const, var, struct, enum, builtin types
_functions = "#cc9947"
_strings = "#a7cc66"
_constants = "#66ccbe"
_comments = "#5f8cd3"

_other1 = "#52cc81"
_other2 = "#cc528b"
