_white = "#f2f2f2"
_gray = "#A6A6A6"
_black = "#212121"
_blacker = "#000000"
_purple = "#9D62D9"
_light_purple = "#BA8EE6" # BA8EE6 B898D9
_blue = "#6291d9"
_light_blue = "#8eb1e5"
_dim_blue = "#264f78"
_dimmer_blue = "#162d45"
_cyan = "#5cccc6"
_neon_green = "#75e67d"
_neon_yellow = "#d0ff00"
_hot_pink = "#e6509b"
_orange = "#fdbe00"
_red = "#e83841"
_green = "#85db18"
