[editor]
foreground = "#e6e6e6"
background = "#212121"
background_highlight = "#000000"
highlight = "#264f78"
highlight_dim = "#162d45"
highlight_loud = "#85db18"

[tokens]
foreground = "#e6e6e6"
punctuation = "#999999"
keywords = "#d35568"
storage = "#d35568"
functions = "#d3a355"
strings = "#a5d355"
constants = "#55d3c2"
comments = "#5585d3"
changed = "#fdbe00"
deleted = "#e83841"
inserted = "#85db18"
