type = "Dark"
name = "zooce-dark"
file = "./vscode/themes/zooce-dark-3-color-theme.json"

[colors]
_white = [
    "editor.foreground",
]
_black = [
    "editor.background",
]
_blacker = [
    "editor.lineHighlightBackground",
    "editorGutter.background",
]
_dim_blue = [
    "editor.findMatchHighlightBackground",
    "editor.hoverHighlightBackground",
    "editor.wordHighlightBackground",
]
_dimmer_blue = [
    "editor.selectionHighlightBackground",
    "editor.symbolHighlightBackground",
]
_neon_yellow = [
    "editorBracketMatch.border",
    "editor.findMatchBorder",
]

[tokenColors]
_white = [
    # rust
    "entity.name.type.rust",

    # "constant.other.caps",
    # "variable",
    # "support.type.property-name",
    # "entity.name.type",
]
_gray = [
    # python
    "constant.character.format.placeholder.other.python",
    "entity.name.function.decorator.python",
    "punctuation.definition.arguments.begin.python",
    "punctuation.definition.arguments.end.python",
    "punctuation.definition.dict.begin.python",
    "punctuation.definition.dict.end.python",
    "punctuation.definition.list.begin.python",
    "punctuation.definition.list.end.python",
    "punctuation.definition.parameters.begin.python",
    "punctuation.definition.parameters.end.python",
    "punctuation.definition.string.begin.python",
    "punctuation.definition.string.end.python",
    "punctuation.parenthesis.begin.python",
    "punctuation.parenthesis.end.python",
    "punctuation.section.class.begin.python",
    "punctuation.section.function.begin.python",
    "punctuation.section.function.lambda.begin.python",
    "punctuation.separator.annotation.python",
    "punctuation.separator.arguments.python",
    "punctuation.separator.colon.python",
    "punctuation.separator.dict.python",
    "punctuation.separator.element.python",
    "punctuation.separator.parameters.python",
    "punctuation.separator.period.python",

    # rust
    "keyword.operator.namespace.rust",
    "punctuation.brackets.curly.rust",
    "punctuation.brackets.round.rust",
    "punctuation.brackets.angle.rust",
    "punctuation.brackets.square.rust",
    "keyword.operator.key-value.rust",
    "punctuation.comma.rust",
    "punctuation.semi.rust",
    "keyword.operator.access.dot.rust",
    "punctuation.definition.string.rust",
    "punctuation.definition.lifetime.rust",
    "entity.name.type.lifetime.rust",
    "punctuation.brackets.attribute.rust",
    "punctuation.definition.attribute.rust",
    "keyword.operator.arrow.skinny.rust",
    "keyword.operator.arrow.fat.rust",

    # "comment.block",
    # "constant.character.format",
    # "entity.name.function.decorator",
    # "keyword.operator",
    # "markup.fenced_code",
    # "meta.attribute",
    # "meta.brace",
    # "meta.diff",
    # "meta.embedded.diff",
    # "meta.separator",
    # "meta.tag",
    # "meta.tag.preprocessor",
    # "punctuation.accessor",
    # "punctuation.brackets",
    # "punctuation.comma",
    # "punctuation.decorator",
    # "punctuation.definition.annotation",
    # "punctuation.definition.arguments",
    # "punctuation.definition.begin",
    # "punctuation.definition.block",
    # "punctuation.definition.bold",
    # "punctuation.definition.constant",
    # "punctuation.definition.dict",
    # "punctuation.definition.end",
    # "punctuation.definition.italic",
    # "punctuation.definition.link",
    # "punctuation.definition.list",
    # "punctuation.definition.metadata",
    # "punctuation.definition.parameters",
    # "punctuation.definition.quote",
    # "punctuation.definition.raw",
    # "punctuation.definition.string",
    # "punctuation.definition.tag",
    # "punctuation.definition.template-expression",
    # "punctuation.parenthesis",
    # "punctuation.section",
    # "punctuation.semi",
    # "punctuation.separator",
    # "punctuation.terminator",
    # "punctuation.other.period",
    # "punctuation.other.comma",
    # "punctuation.definition.imports",
    # "punctuation.definition.annotation-arguments",
    # "punctuation.definition.entity",
    # "punctuation.definition.keyValuePair.toml",
    # "punctuation.definition.inlinetable.toml",
    # "punctuation.definition.array.toml",
    # "storage.type.annotation",
    # "string.quoted.docstring",
]
_keywords = [
    # python
    "keyword.control.flow.python",
    "keyword.control.import.python",
    "keyword.operator.arithmetic.python",
    "keyword.operator.assignment.python",
    "keyword.operator.comparison.python",
    "keyword.operator.logical.python",
    "keyword.operator.python",
    "storage.type.function.python",

    # rust
    "keyword.control.rust",
    "keyword.operator.assignment.equal.rust",
    "keyword.operator.assignment.rust",
    "keyword.operator.logical.rust",
    "keyword.other.fn.rust",
    "keyword.other.rust",
    "keyword.operator.borrow.and.rust",
    "keyword.operator.comparison.rust",
    "keyword.operator.dereference.rust",
    "keyword.operator.range.rust",
    "keyword.operator.math.rust",

    # "entity.name.tag",
    # "keyword",
    # "keyword.operator.delete",
    # "keyword.operator.new",
    # "markup.heading",
    # "punctuation.definition.keyword",
    # "punctuation.separator.namespace",
]
_light_purple = [
    # "entity.name.type",
]
_storage = [
    # python
    "storage.type.class.python",
    "storage.type.string.python",
    "storage.type.function.lambda.python",

    # rust
    "storage.type.rust",
    "storage.modifier.mut.rust",
    "entity.name.type.numeric.rust",
    "entity.name.type.primitive.rust",
    "entity.name.type.option.rust",
    "entity.name.type.result.rust",

    # "keyword.control.svelte",
    # "punctuation.definition.keyword.svelte",
    # "storage",
    # "support.type",
    # "support.class",
    # "constant.other.database-name",
]
_strings = [
    # python
    "string.quoted.multi.python",
    "string.quoted.single.python",

    # rust
    "string.quoted.double.rust",

    # "string",
    # "support.constant.font-name",
    # "support.constant.property-value",
    # "constant.other.table-name",
    # "entity.name.type",
]
_functions = [
    # python
    "entity.name.function.python",
    "meta.function-call.generic.python",
    "support.function.builtin.python",

    # rust
    "entity.name.function.rust",
    "meta.attribute.rust",

    # "entity.name.function",
    # "entity.other.attribute-name",
    # "meta.function-call",
    # "support.function",
    # "entity.name.function.preprocessor",
    # "entity.name.section",
]
_constants = [
    # python
    "constant.character.escape.python",
    "constant.character.format.placeholder.other.python",
    "variable.language.special.self.python",
    "variable.parameter.function.language.special.self.python",
    "constant.language.python",
    "constant.numeric.float.python",
    "constant.numeric.dec.python",

    # rust
    "entity.name.function.macro.rust",
    "variable.language.self.rust",
    "constant.character.escape.rust",
    "constant.language.bool.rust",
    "constant.numeric.decimal.rust",

    # "variable.language", # like `self`
    # "comment.line",
    # "comment.block.html",
    # "comment.block.xml",
    # "markup.raw",
    # "markup.inline",
]
_neon_yellow = [
    # python
    # "constant.language.python",
    # "constant.numeric.float.python",
    # "constant.numeric.dec.python",

    # rust
    # "constant.language.bool.rust",
    # "constant.numeric.decimal.rust",

    # "constant.numeric",
    # "constant.language",
    # "constant.character",
    # "constant.other",
    # "support.constant",
    # "keyword.constant",
]
_comments = [
    # python
    "comment.line.number-sign.python",
    "string.quoted.docstring.multi.python",
    "string.quoted.docstring.raw.multi.python",

    # rust
    "comment.line.double-slash.rust",
    "comment.line.documentation.rust",

    # "variable.language", # like `self`
    # "comment.line",
    # "comment.block.html",
    # "comment.block.xml",
]
_orange = [
    # "markup.changed",
]
_red = [
    # "markup.deleted",
]
_green = [
    # "markup.inserted",
]


