[editor]
foreground = "#f2f2f2"
background = "#2b2a2a"
background_highlight = "#000000"
highlight = "#bf353f"
highlight_dim = "#162d45"
border_loud = "#85db18"
accent = "#3c78d2"
changed = "#dc9118"
deleted = "#dc1836"
inserted = "#95dc18"
unknown = "#18dcc2"

[tokens]
foreground = "#f2f2f2"
punctuation = "#8a8a8a"
keywords = "#b26ef7"
functions = "#2be0d7"
strings = "#8eb1e5"
constants = "#d0ff00"
other = "#72aafd"
comments = "#ff43a1"
changed = "#fdbe00"
deleted = "#e83841"
inserted = "#85db18"
